    <!-- filtro de avaliações -->
    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
            <div class="panel panel-default">
              <div class="panel-body">
                  <div class="form-group">
                    <form class="form-inline" role="form" method="POST" action="#">
                        <div class="row">
                          <div class='col-sm-4'>
                            <div class="form-group">
                              <label for="disabledTextInput"><?= $formPesquisa->get('aba')->getLabel(); ?></label>
                              <?= $this->formElement($formPesquisa->get('aba')); ?>
                            </div>
                          </div>

                          <div class='col-sm-4'>
                            <div class="form-group">
                              <label for="disabledTextInput"><?= $formPesquisa->get('empresa')->getLabel(); ?></label>
                              <?= $this->formElement($formPesquisa->get('empresa')); ?>
                            </div>
                          </div>

                          <div class='col-sm-4'>
                            <div class="form-group">
                              <label for="disabledTextInput"><?= $formPesquisa->get('mes')->getLabel(); ?></label>
                              <?= $this->formElement($formPesquisa->get('mes')); ?>
                            </div>
                          </div>

                          
                        </div>

                        <div class="row" style="margin-top:20px;">
                          
                          <div class='col-sm-4'>
                            <div class="form-group">
                              <label for="disabledTextInput"><?= $formPesquisa->get('ano')->getLabel(); ?></label>
                              <?= $this->formElement($formPesquisa->get('ano')); ?>
                            </div>
                          </div>

                          <div class='col-sm-4'>
                            <div class="form-group">
                              <label for="disabledTextInput"><?= $formPesquisa->get('respondida')->getLabel(); ?></label>
                              <?= $this->formElement($formPesquisa->get('respondida')); ?>
                            </div>
                          </div>

                        </div>

                        <div class="row" style="margin-top:20px;">
                          <button type="submit" name="limpar" class="btn btn-default" style="float: right;margin-right: 20px;">
                          <img src="<?= $this->basePath('img/limpar.png'); ?>"> Limpar</button>
                          <button type="submit" class="btn btn-info" name="pesquisar" style="float: right;margin-right: 10px;background: #036fb7 none repeat scroll 0 0;">
                          <img src="<?= $this->basePath('img/pesquisar.png'); ?>" alt="Pesquisar"> Pesquisar</button>
                        </div>
                      </div>
                  </form>
                </div>
              </div>
          </div>
    </div>

    <!-- LISTAGEM DAS AVALIAÇÕES -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de avaliações</h3>
            </div>
            <div class="panel-body">
              <?php if($avaliacoes->count() > 0): ?>
                <?php if($numeroAba == 6 || $numeroAba == 7): ?>
                  <!-- AVALIAÇÃO DE MÉDICO -->
                  <table class="table">
                    <tr>
                      <th style="text-align: center">Empresa</th>
                      <th style="text-align: center">Médico</th>
                      <th style="text-align: center">Mês</th>
                      <th style="text-align: center">Ano</th>
                      <th style="text-align: center">Auditar avaliações</th>
                    </tr>
                    <?php foreach($avaliacoes as $avaliacao): ?>
                      <tr>
                        <td style="text-align: center"><?= $avaliacao['nome_empresa']; ?></td>
                        <td style="text-align: center"><?= $avaliacao['nome_medico']; ?></td>
                        <td style="text-align: center"><?= $this->numeroMes($avaliacao['mes']); ?></td>
                        <td style="text-align: center"><?= $avaliacao['ano']; ?></td>
                        <td style="text-align: center;">
                          <img src="<?= $this->basePath('img/auditar.png'); ?>" title="Editar" 
                          onclick="location.href='<?= $this->url($aba, array('id' => $avaliacao['id'])); ?>'" style="cursor: pointer;">
                        </td>
                      </tr>  
                    <?php endforeach; ?>
                  </table>
                <?php else: ?>
                  <!-- AVALIAÇÃO DE CLÍNICA -->
                  <table class="table">
                    <tr>
                      <th style="text-align: center">Empresa</th>
                      <th style="text-align: center">Mês</th>
                      <th style="text-align: center">Ano</th>
                      <th style="text-align: center"><?php echo $avaliacoesRespondidas == true ? 'Auditar' : 'Responder'; ?> avaliações</th>
                    </tr>
                    <?php foreach($avaliacoes as $avaliacao): ?>
                      <tr>
                        <td style="text-align: center"><?= $avaliacao['nome_empresa']; ?></td>
                        <td style="text-align: center"><?= $this->caracterVazio($this->numeroMes($avaliacao['mes'])); ?></td>
                        <td style="text-align: center"><?= $this->caracterVazio($avaliacao['ano']); ?></td>
                        <td style="text-align: center;">
                        <?php if($avaliacoesRespondidas): ?>
                          <?php if($aba == 'avaliacaoAtaAudicao'): ?>
                            <img src="<?= $this->basePath('img/auditar.png'); ?>" title="Auditar avaliação" 
                            onclick="location.href='<?= $this->url($aba, array('mes' => $avaliacao['mes'],  'ano' => $avaliacao['ano'], 'empresa' => $avaliacao['empresa'])); ?>'" style="cursor: pointer;">
                          <?php else: ?>
                          
                            <img src="<?= $this->basePath('img/auditar.png'); ?>" title="Auditar avaliação" 
                            onclick="location.href='<?= $this->url($aba, array('id' => $avaliacao['id'])); ?>'" style="cursor: pointer;">
                          <?php endif; ?>
                        <?php else: ?>
                        
                          <!-- Avaliações não respondidas -->
                           <img src="<?= $this->basePath('img/novo.png'); ?>" title="Responder avaliação" 
                            onclick="location.href='<?= $this->url('responderAvaliacao', array('aba' => $numeroAba, 'empresa' => $avaliacao['id_empresa'], 'ano' => $ano, 'mes' => $mes)); ?>'" style="cursor: pointer;">

                          
                        <?php endif; ?>
                        </td>
                      </tr>  
                    <?php endforeach; ?>
                  </table>
              <?php endif; ?>
                
            <?php else: ?>
              <div class="alert alert-info">Nenhuma avaliação encontrada!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($avaliacoes,
                                        'Sliding',
                                        'view/paginator', array('route' => 'avaliacoesaudicaonovo')); 
          ?>
        </div>
      </div>