 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('avaliacoesaudicaonovo'); ?>">Avaliações</a></li>
      <li >Avaliação qualitativa</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">
                Avaliação qualitativa do mês de <?= $this->numeroMes($avaliacao->mes); ?>/<?= $avaliacao->ano; ?> - <?= $medico->nome_medico; ?>
              </h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/umacoluna', array('form'=> $formQualitativa, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>

    </div>