<div class="center">
        <a href="javascript:void(0)" class="logo"><img src="<?= $this->basePath('css/login/images/logo.png') ?>"></a>
        
        <article class="bloco-4">
        	<form action="#" method="POST" name="frmAvaliacao">
	            <h2>Siga Avaliação</h2>
	            <div class="cor1">
	                <input type="text" name="login" placeholder="Nome"/>
	                <input type="password" name="password" placeholder="Senha"/>
	                <input type="submit" name="qualidade_mensal" value="Enviar"/>
	            </div>
	        </form>
        </article>
        
        <article class="bloco-4">
        	<form action="#" method="POST" name="frmDiario">
	            <h2>Diário de Bordo</h2>
	            <div class="cor2">
	                <input type="text" name="login" placeholder="Nome"/>
	                <input type="password" name="password" placeholder="Senha"/>
	                <input type="submit" name="qualidade_diaria" value="Enviar"/>
	            </div>
	        </form>
        </article>
        
        <article class="bloco-4">
        	<form action="#" method="POST" name="frmCallCenter">
	            <h2>Avaliação Call Center</h2>
	            <div class="cor3">
	                <input type="text" name="login" placeholder="Nome"/>
	                <input type="password" name="password" placeholder="Senha"/>
	                <input name="callcenter" type="submit" value="Enviar"/>
	            </div>
	        </form>
        </article>
        
        <article class="bloco-4">
            <form action="#" method="POST" name="frmAvaliacaoMedica">
	            <h2>9Box - Avaliação Médica</h2>
	            <div class="cor4">
	                <input type="text" name="login" placeholder="Nome"/>
	                <input type="password" name="password" placeholder="Senha"/>
	                <input name="medicos" type="submit" value="Enviar"/>
	            </div>
	        </form>
        </article>


        <article class="bloco-4">
            <form action="#" method="POST" name="frmAvaliacaoMedica">
	            <h2>Simulador Médico</h2>
	            <div class="cor5">
	            	<input type="hidden" value="5" name="simulador">
	                <input type="text" name="login" placeholder="Nome"/>
	                <input type="password" name="password" placeholder="Senha"/>
	                <input type="submit" name="simulador" value="Enviar"/>
	            </div>
	        </form>
        </article>




        <article class="bloco-4">
            <form action="http://w9boxrh.tempsite.ws/login" method="POST" name="frmAvaliacaoMedica">
	            <h2>RH</h2>
	            <div class="cor6" style="text-align: center;">
	            	<input type="hidden" value="5" name="simulador">
	                <input type="text" name="cpf" style="margin-bottom: 0px;" id="cpf" placeholder="cpf"/>
	                <label style="font-weight: bold;">OU</label>
	                <input type="text" name="email" placeholder="Email"/>
	                <input type="password" name="password" placeholder="Senha"/>
	                <input type="submit" name="simulador" value="Enviar"/>
	            </div>
	        </form>
        </article>

        <article class="bloco-4">
            <form action="http://mapaalliar.tempsite.ws/login" method="POST" name="frmAvaliacaoMedica">
	            <h2>Mapa</h2>
	            <div class="cor7">
	            	<input type="hidden" value="5" name="simulador">
	                <input type="text" name="login" placeholder="Nome"/>
	                <input type="password" name="password" placeholder="Senha"/>
	                <input type="submit" name="simulador" value="Enviar"/>
	            </div>
	        </form>
        </article>
        
    </div>

    <script type="text/javascript">
	  $(document).ready(function() {
		$("#cpf").mask("999.999.999-99");
	  });
</script>