 
<div class="container theme-showcase" role="main">
  <div class="row">
      <div class="panel panel-default">
      <div class="panel-heading">
          <h3 class="panel-title">Alterar empresa</h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
              <?php echo $this->partial('form/generic', array('form'=> $formEmpresa, 'route'=> '')) ?>

        </div>
      </div>
  </div>
</div>
</div>