<div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">

      <button type="button" class="btn btn-danger" onclick="location.href='<?= $this->url('graficoPersonalizadoAvaliacoesDiarias', array('limpar' => 'S')); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/limpar.png') ?>" alt="Novo">
      Limpar parâmetros</button>
      
      <button type="button" class="btn btn-success" onclick="location.href='<?= $this->url('visualizarGraficoPersonalizadoAvaliacoesDiarias'); ?>'" style="float: right;margin-right: 5px;">
      <img src="<?php echo $this->basePath('img/grafico.png') ?>" alt="Novo">
      Gerar gráfico</button>
</div>

 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
  <ol class="breadcrumb" style="margin-bottom: 0px;">
    <li><a href="<?= $this->url('administradorAvaliacoesDiarias'); ?>">Lista de avaliações</a></li>
    <li><a href="<?= $this->url('graficoAvaliacoesDiarias'); ?>">Gráfico</a></li>
    <li class="active">Gráfico personalizado</li>
  </ol>
</div>


    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Inserir parâmetros para gráfico personalizado</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formGrafico, 'route'=> '')) ?>
            </div>
          </div>
      </div>
    </div>
    </div>

    <?php if($formEmpresas): ?>

      <div class="container theme-showcase" role="main">
        <div class="row">
            <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Vincular empresas</h3>
              </div>
              <div class="panel-body">
                  <div class="form-group">
                    <?php echo $this->partial('form/generic', array('form'=> $formEmpresas, 'route'=> '')) ?>
              </div>
            </div>
        </div>
      </div>
    </div>

    <?php if($empresas->count() > 0): ?>
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Empresas vinculadas</h3>
            </div>
            <div class="panel-body">
              <table class="table">
                <tr>
                  <th style="text-align: center">Empresa</th>
              </tr>

              <?php 
              foreach ($empresas as $empresa): 
              ?>
              <tr>
                <td style="text-align: center"><?= $empresa->nome_empresa ?></td>
              </tr>
            <?php endforeach; ?>
            </table>
            </div>
          </div>
        </div>
      </div>
    <?php endif; ?>


    <div class="container theme-showcase" role="main">
        <div class="row">
            <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Vincular campos</h3>
              </div>
              <div class="panel-body">
                  <div class="form-group">
                    <?php echo $this->partial('form/generic', array('form'=> $formCampos, 'route'=> '')) ?>
              </div>
            </div>
        </div>
      </div>
    </div>

    <?php endif; ?>

    <?php if($campos->count() > 0): ?>
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Campos vinculados</h3>
            </div>
            <div class="panel-body">
              <table class="table">
                <tr>
                  <th style="text-align: center">Campos</th>
              </tr>

              <?php 
              foreach ($campos as $campo): 
              ?>
              <tr>
                <td style="text-align: center"><?= $campo->label ?></td>
              </tr>
            <?php endforeach; ?>
            </table>
            </div>
          </div>
        </div>
      </div>
    <?php endif; ?>

    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      
      <button type="button" class="btn btn-success" onclick="location.href='<?= $this->url('visualizarGraficoPersonalizadoAvaliacoesDiarias'); ?>'" style="float: right;margin-right: 5px;">
      <img src="<?php echo $this->basePath('img/grafico.png') ?>" alt="Novo">
      Gerar gráfico</button>
    </div>

    <script type="text/javascript">
	    $(document).ready(function() {
			  $("#inicio").mask("99/99/9999");
        $("#fim").mask("99/99/9999");
		  });
    </script>