 <h1>Avaliação call center - Data de referência: <?= $this->converterData($avaliacao->data_referencia); ?></h1>

<div style="display:none"><input name="unidade" id="unidade" value="Formulário de Auto Avaliação" type="text"></div>
<a href="<?php  
		switch ($usuario['id_usuario_tipo']) {
			case 11:
				echo $this->url('listarAvaliacoesCallCenter');
				break;
			case 4:
          		echo $this->url('listaAvaliacoesCallCenterAdm');
				break;
			default:
		  		echo $this->url('administradorAvaliacoesCallCenter');
				break;
		}
		?>" class="acesso-usuario db"> Lista de avaliações</a>
<div class="formulario restrito">

<div class="pager-form">
  <a class="link-arquivos active" data-slide-index="4" href="#">Call center</a>
</div>

<div style="max-width: 100%;" class="bx-wrapper"><div style="width: 100%; overflow: hidden; position: relative; height: auto;" class="bx-viewport"><ul style="width: 615%; position: relative; transition-duration: 0s; transform: translate3d(0px, 0px, 0px);" class="slider-form">
<li style="float: left; list-style: outside none none; position: relative; width: 992px;"> 

<div class="form-auditoria">


<?php 
  //CRIAR UMA PARTIAL, USAR FORM E CAMPOS
  if($formAvaliacaoOriginal){
  	echo $this->partial('form/exibircallcenter', array('form'=> $formAvaliacao, 'avaliacao' => $avaliacao, 'formOriginal' => $formAvaliacaoOriginal, 'avaliacaoOriginal' => $avaliacaoOriginal, 'campos'=> $campos));
  }else{
  	echo $this->partial('form/callcenter', array('form'=> $formAvaliacao, 'campos'=> $campos));
  }

?>

</div>
<!--<p><input name="enviar" id="enviar" value="Enviar" type="submit"></p>-->


</li>
</ul>
</div>

</div>
</div>

<style type="text/css">
  .errovalidacao{
    font-weight: bold;
    color: red;
  }
</style>