 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
  <ol class="breadcrumb" style="margin-bottom: 0px;">
    <?php if($usuario['id_usuario_tipo'] == 4): ?>
      <li><a href="<?= $this->url('listaAvaliacoesCallCenterAdm'); ?>">Lista de avaliações</a></li>
    <?php else: ?>
      <li><a href="<?= $this->url('administradorAvaliacoesCallCenter'); ?>">Lista de avaliações</a></li>
      <li><a href="<?= $this->url('grafico'); ?>">Filtros do gráfico</a></li>
    <?php endif; ?>
    <li class="active">Visualizar gráfico</li>
  </ol>
</div>

<div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <canvas id="canvas" height="450" width="600"></canvas>
</div>

      <script>
        var randomScalingFactor = function(){ return Math.round(Math.random()*100)};

        var lineChartData = {
          labels : [
          <?php foreach ($somaAvaliacoes as $avaliacao) : ?>
            "<?= $avaliacao['label'] ?>",
          <?php endforeach; ?>
          ],
          datasets : [
            {
              label: "avaliacao",
              fillColor: "rgba(151,187,205,0.2)",
              strokeColor: "rgba(151,187,205,1)",
              pointColor: "rgba(151,187,205,1)",
              pointStrokeColor: "#fff",
              pointHighlightFill: "#fff",
              pointHighlightStroke: "rgba(151,187,205,1)",
              data : [
              <?php foreach ($somaAvaliacoes as $avaliacao) : ?>
                "<?= $avaliacao['valor'] ?>",
              <?php endforeach; ?>  
                ]
            }
          ]

        }
        window.onload = function(){
          var ctx = document.getElementById("canvas").getContext("2d");
          window.myLine = new Chart(ctx).Line(lineChartData, {
            responsive : true
          });
        }
      </script>

