<?php if(!$this->params)$this->params = array();?>
<?php $form->prepare(); ?>

<?php if($this->route):?>
    <?php $form->setAttribute('action', $this->url($this->route, $this->params)); ?>
<?php else: ?>
	<?php $form->setAttribute('action', "#"); ?>
<?php endif;?>

<?= $this->form()->openTag($form); ?>
<?php $row = 0; ?>
<?php foreach ($form->getElements() as $element): ?>
		<div class="row">
	        <div class='col-sm-12'>
                <div class="form-group" id="group-<?= $element->getName(); ?>">
	        
	        <label for="<?=$element->getName()?>"><?=$element->getLabel()?></label>	
	        	
	     		</div>
            </div>
        </div>
        
        <div class="row" style="margin-bottom: 20px;">
	        <div class='col-sm-12'>
             
	        
	        	<?= $this->formElement($element); ?>
	        	<?= $this->formElementErrors($element, array('class' => 'alert alert-danger')); ?>
	     		
            </div>
        </div>

<?php endforeach; ?>
</div>
<div class="row" style="margin-top:20px;">

	<?php if(isset($this->botao)): ?>
		<?= $this->botao; ?>
	<?php else: ?>
	<button type="submit" class="btn btn-success" style="float: right;margin-right: 10px;">
		<img src="<?php echo $this->basePath('img/salvar.png') ?>" alt="Salvar" title="Salvar">
		Salvar
	</button>

<?php endif; ?>
	
	<?php 
	if($this->imprimir){
		echo $imprimir;
	}
	?>
</div>


<?= $this->form()->closeTag($form); ?>