 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
            <div class="panel panel-default">
              <div class="panel-body">
                  <div class="form-group">
                    <form class="form-inline" role="form" method="POST" action="#">
                        <div class="row">
                          <div class='col-sm-4'>
                            <div class="form-group">
                               <label for="disabledTextInput"><?=$formPesquisa->get('nome_empresa')->getLabel()?></label>
                               <?= $this->formElement($formPesquisa->get('nome_empresa')); ?>
                            </div>
                          </div>

                          <div class='col-sm-4'>
                            <div class="form-group">
                              <label for="disabledTextInput"><?= $formPesquisa->get('nome_responsavel')->getLabel(); ?></label>
                              <?= $this->formElement($formPesquisa->get('nome_responsavel')); ?>
                            </div>
                          </div>

                          <div class='col-sm-4'>
                            <div class="form-group">
                              <label for="disabledTextInput"><?= $formPesquisa->get('email')->getLabel(); ?></label>
                              <?= $this->formElement($formPesquisa->get('email')); ?>
                            </div>
                          </div>

                        </div>

                        <div class="row" style="margin-top:20px;">
                          <div class='col-sm-4'>
                            <div class="form-group">
                              <label for="disabledTextInput"><?= $formPesquisa->get('ativo')->getLabel(); ?></label>
                              <?= $this->formElement($formPesquisa->get('ativo')); ?>
                            </div>
                          </div>
                        </div>

                        <div class="row" style="margin-top:20px;">
                          <button type="submit" class="btn btn-success" style="float: right;margin-right: 10px;">
                          <img src="<?= $this->basePath('img/pesquisar.png'); ?>" alt="Pesquisar"> Pesquisar</button>
                          <button  type="submit" name="limpar" class="btn btn-default" style="float: right;margin-right: 20px;">
                          <img src="<?= $this->basePath('img/limpar.png'); ?>"> Limpar</button>
                        </div>
                      </div>
                  </form>
                </div>
              </div>
          </div>
    </div>

    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
       <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('empresaNovo'); ?>'" style="float: right;width:100px;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo</button>

      <ol class="breadcrumb" style="margin-bottom: 0px;">
        <li><a href="<?= $this->url('home'); ?>">Home</a></li>
        <li class="active">Empresas</li>
      </ol>
    </div>
    <!-- LISTAGEM DOS CHAMADOS -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de empresas</h3>
            </div>
            <div class="panel-body">
              <?php if($empresas->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Nome da empresa</th>
                    <th style="text-align: center">Nome responsável</th>
                    <th style="text-align: center">Email</th>
                    <th style="text-align: center">Email</th>
                    <th style="text-align: center">Email</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($empresas as $empresa): ?>
                <tr>
                  <td style="text-align: center"><?= $empresa['nome_empresa']; ?></td>
                  <td style="text-align: center"><?= $empresa['nome_responsavel']; ?></td>
                  <td style="text-align: center"><?= $this->caracterVazio($empresa['email']); ?></td>
                  <td style="text-align: center"><?= $this->caracterVazio($empresa['email2']); ?></td>
                  <td style="text-align: center"><?= $this->caracterVazio($empresa['email3']); ?></td>
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/check.png'); ?>" title="Personalizar avaliações" 
                    onclick="location.href='<?= $this->url('personalizarAvaliacao', array('empresa' => $empresa['id'], 'aba' => 2)); ?>'" style="cursor: pointer;">
                    
                    <span style="margin-right:4px;"></span>

                    <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('empresaAlterar', array('id' => $empresa['id'])); ?>'" style="cursor: pointer;">
                    
                    <span style="margin-right:4px;"></span>  
                    
                    <img src="<?= $this->basePath('img/deletar.png'); ?>" title="Deletar" style="cursor: pointer;" onclick="alerta('<?= $this->url('empresaDeletar', array('id' => $empresa['id'])) ?>', 'desativar');">
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhuma empresa encontrada!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($empresas,
                                        'Sliding',
                                        'view/paginator', array('route' => 'empresa')); 
          ?>
        </div>
      </div>