<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('SIGA - Auto avaliação'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles
<link rel="shortcut icon" href="http://mobweb.com.br/simulador/assets/images/icons/favicon.png"> -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        
            ->prependStylesheet($this->basePath() . '/css/remuneracaoMedica/layout.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-slider.min.css')
            ->prependStylesheet($this->basePath() . '/css/remuneracaoMedica/boilerplate.css')
            ->prependStylesheet($this->basePath() . '/css/remuneracaoMedica/content-box.css')
            ->prependStylesheet($this->basePath() . '/css/remuneracaoMedica/default.css')
            ->prependStylesheet($this->basePath() . '/css/remuneracaoMedica/default_002.css')
            ->prependStylesheet($this->basePath() . '/css/remuneracaoMedica/utils.css')
            ->prependStylesheet($this->basePath() . '/css/remuneracaoMedica/backgrounds.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css'); ?>

        <!-- Scripts -->
        <?php 
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap-slider.min.js')
            ->prependFile($this->basePath() . '/js/easyPieChart/jquery.easypiechart.js')
            ->prependFile($this->basePath() . '/js/justgage.js')
            ->prependFile($this->basePath() . '/js/raphael-2.1.4.min.js')
            ->prependFile($this->basePath() . '/js/Chart.js-master/Chart.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
        ; ?>

        
    </head>
    <body class="ng-scope" ng-controller="indexController">
        <div id="sb-site">
            <div id="page-wrapper">
                <div id="page-header" class="bg-gradient-9">
                    <div id="header-logo" class="logo-bg">
                        <img src="<?= $this->basePath('img/logo_simulador.png'); ?>" style="margin-top:5px;">
                    </div>
                    <div id="header-nav-left">
                        <div id="page-title" style="position:absolute;margin-top:10px;margin-left:20px;">
                            <h2 style="color:#fff">Simulador Médico</h2>
                            <p style="color:#fff">Simulador para classificação de remuneração médica.</p>
                        </div>                        
                    </div>
                    <div id="header-nav-right">
                        <a href="#" class="hdr-btn" id="fullscreen-btn" title="Fullscreen">
                            <i class="glyph-icon icon-arrows-alt"></i>
                        </a>
                    </div>
                </div>                

                <div style="height: 891px;" id="page-sidebar">
                    <div style="height: 891px;" class="scroll-sidebar">


                        <ul class="sf-js-enabled sf-arrows" id="sidebar-menu">
                            <li class="header"><span>Menu</span></li>
                            <li>
                                <a href="<?= $this->url('simulador'); ?>" title="Simulador">
                                    <i class="glyph-icon icon-linecons-params"></i>
                                    <span>Simulador</span>
                                    <!-- <span class="bs-label label-danger">
                                        HOME
                                    </span> -->                                    
                                </a>
                            </li>
                            <li class="no-menu">
                                <a href="<?= $this->url('relacionamento'); ?>" title="Prg. Relacionamento">
                                    <i class="glyph-icon icon-linecons-diamond"></i>
                                    <span>Lista de médicos</span>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="<?= $this->url('logout'); ?>" title="Sair">
                                    <i class="glyph-icon icon-arrow-circle-o-right"></i>
                                    <span>Sair</span>
                                </a>
                            </li>                            
                        </ul>


                    </div>
                </div>

    <?php echo $this->content; ?>

    <hr>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
<style>
    .nivelClass {
        color: #C62828;
        font-weight: bold;
        background: #f5f5f5;
    }
</style>