    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">        
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoMetaMensal'); ?>'" style="float:right;margin-left: 5px;">       
        <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo"> Nova meta mensal</button>

      <button type="button" class="btn btn-success" onclick="location.href='<?= $this->url('replicarMetaMensal'); ?>'" style="float: right;margin-left: 5px;">
      <img src="<?php echo $this->basePath('img/replicar.png') ?>" alt="Meta diária">
      Replicar meta mensal</button>

      <button type="button" class="btn btn-warning active" style="float: right;margin-left: 5px;">
      <img src="<?php echo $this->basePath('img/metaMensal.png') ?>" alt="Meta mensal">
      Meta mensal</button>

      <button type="button" class="btn btn-danger" onclick="location.href='<?= $this->url('indexMetasAgendamento'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/metaDiaria.png') ?>" alt="Meta diária">
      Meta diária</button>


      <ol class="breadcrumb" style="margin-bottom: 0px;">
        <li><a href="<?= $this->url('administradorAvaliacoesCallCenter'); ?>">Lista de avaliações</a></li>
        <li class="active">Metas de agendamento</li>
      </ol>
    </div>




    <!-- LISTAGEM DOS CHAMADOS -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Metas de agendamento mensal</h3>
            </div>
            <div class="panel-body">
              <?php if($metas->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Empresa</th>
                    <th style="text-align: center">Mês</th>
                    <th style="text-align: center">Meta</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($metas as $meta): ?>
                <tr>
                  <td style="text-align: center"><?= $meta['nome_empresa']; ?></td>
                  <td style="text-align: center"><?= $meta['mes'].'/'.$meta['ano']; ?></td>
                  <td style="text-align: center"><?= $meta['valor']; ?></td>
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" style="cursor: pointer;"  onclick="location.href='<?= $this->url('alterarMetaMensal', array('id' => $meta['id'])); ?>'">

                     <span style="margin-right:4px;"></span>  
                    
                    <img src="<?= $this->basePath('img/deletar.png'); ?>" title="Deletar" style="cursor: pointer;" onclick="alertaComum('<?= $this->url('deletarMetamensal', array('id' => $meta['id'])) ?>', 'Deseja realmente deletar a meta?');">
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhuma meta mensal encontrada!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($metas,
                                        'Sliding',
                                        'view/paginator', array('route' => 'indexMetasMensais')); 
          ?>
        </div>
      </div>