<?php 
	$categoria = '';
	$quantidadeCampos = 0;
?>
<?php foreach ($campos as $key => $campo) {

	if($campo['aparecer'] == 'S'){
		$quantidadeCampos++;

		//se for uma nova categoria escrever o título da categoria
		if($categoria != $campo['nome_categoria']){
			$categoria = $campo['nome_categoria'];
			echo '<h3>'.$campo['nome_categoria'].'</h3>';
		}

		//pegar elemento do form
		$elemento = $form->get($campo['nome_campo']);
		$elementoOriginal = $formOriginal->get($campo['nome_campo']);

		//escrever campo
		echo '<p class="pergunta-'.$quantidadeCampos.'" style="margin-top:7px;">'.$elemento->getLabel();
		echo '</p>';
		
		echo '<p class="pergunta-'.$quantidadeCampos.'2">';
		echo $this->formElement($elemento);
		echo $this->formElementErrors($elemento, array('class' => 'errovalidacao'));

		echo '<div id="div_'.$campo['nome_campo'].'" style="display:none;">';
		echo $this->formElement($elementoOriginal);
		echo '</div>';			

		echo '</p>';

		?>
		<div style="float: right;">
		<?php if($formOriginal && $avaliacao[$campo['nome_campo']] != $avaliacaoOriginal[$campo['nome_campo']]): ?>
			<label style="display:none;" id="esconder_<?= $campo['nome_campo']; ?>">
			        <a onclick="$('#div_<?= $campo['nome_campo']; ?>').hide();$('#esconder_<?= $campo['nome_campo']; ?>').hide();">
			        	<img src="<?= $this->basePath('img/auditar.png'); ?>">Esconder
			    	</a>
			</label>

			<label>
			        <a onclick="$('#div_<?= $campo['nome_campo'] ?>').show();$('#esconder_<?= $campo['nome_campo'] ?>').show();">
			        	<img src="<?= $this->basePath('img/ok.png'); ?>">Visualizar resp. original
			    	</a>
			</label>
		<?php endif; ?>


		</div>

<?php
	}
}

?>
