<?php 
	$categoria = '';
	$quantidadeCampos = 0;
?>
<?php foreach ($campos as $campo) {

	if($campo['aparecer'] == 'S'){
		$quantidadeCampos++;
		//se for uma nova categoria escrever o título da categoria
		if($categoria != $campo['nome_categoria']){
			$categoria = $campo['nome_categoria'];
			echo '<h3>'.$campo['nome_categoria'].'</h3>';
		}

		//pegar elemento do form
		$elemento = $form->get($campo['nome_campo']);
		//escrever campo
		echo '<p class="pergunta-'.$quantidadeCampos.'">'.$elemento->getLabel();
		echo $this->formElement($elemento);
		echo $this->formElement($form->get('observacoes_'.$campo['nome_campo']));
		echo $this->formElement($form->get('anexo_'.$campo['nome_campo']));
		echo '</p>';
	}
}

?>
