<?php if(!$this->params)$this->params = array();?>
<?php $form->prepare(); ?>

<?php if($this->route || $this->route):?>
    <?php $form->setAttribute('action', $this->url($this->route, $this->params)); ?>
<?php else: ?>
	<?php $form->setAttribute('action', "#"); ?>
<?php endif;?>

<?= $this->form()->openTag($form); ?>
<?php $row = 0; ?>
<?php foreach ($form->getElements() as $element): ?>

		<div class="row" style="margin-bottom: 5px;">
	        <div class='col-sm-3'>
	        	<label for="<?=$element->getName()?>" style="width:250px;"><?=$element->getLabel()?></label>	
            </div>
            <div class="col-sm-9">
	        		<?= $this->formElement($element); ?>
	        		<?= $this->formElementErrors($element, array('class' => 'alert alert-danger')); ?>
            </div>
        </div>
        <?php 
			if($element->getLabel() == '* Campo obrigatório?'){
				echo '<hr>';
			}
		?>

<?php endforeach; ?>

<div class="row" style="margin-top:20px;">
	<button type="submit" class="btn btn-success" style="float: right;margin-right: 10px;">
		<img src="<?php echo $this->basePath('img/salvar.png') ?>" alt="Salvar">
		Salvar
	</button>
</div>


<?= $this->form()->closeTag($form); ?>