    <!-- filtro de avaliações -->
    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
            <div class="panel panel-default">
              <div class="panel-body">
                  <div class="form-group">
                    <form class="form-inline" role="form" method="POST" action="#">
                        <div class="row">
                          <div class='col-sm-4'>
                            <div class="form-group">
                              <label for="disabledTextInput"><?= $formPesquisa->get('empresa')->getLabel(); ?></label>
                              <?= $this->formElement($formPesquisa->get('empresa')); ?>
                            </div>
                          </div>

                          <div class='col-sm-4'>
                            <div class="form-group">
                              <label for="disabledTextInput"><?= $formPesquisa->get('mes')->getLabel(); ?></label>
                              <?= $this->formElement($formPesquisa->get('mes')); ?>
                            </div>
                          </div>

                          <div class='col-sm-4'>
                            <div class="form-group">
                              <label for="disabledTextInput"><?= $formPesquisa->get('ano')->getLabel(); ?></label>
                              <?= $this->formElement($formPesquisa->get('ano')); ?>
                            </div>
                          </div>
                        </div>
                        <div class="row" style="margin-top:20px;">
                          <button type="submit" name="limpar" class="btn btn-default" style="float: right;margin-right: 20px;">
                          <img src="<?= $this->basePath('img/limpar.png'); ?>"> Limpar</button>
                          <button type="submit" class="btn btn-info" name="pesquisar" style="float: right;margin-right: 10px;background: #036fb7 none repeat scroll 0 0;">
                          <img src="<?= $this->basePath('img/pesquisar.png'); ?>" alt="Pesquisar"> Pesquisar</button>
                        </div>
                      </div>
                  </form>
                </div>
              </div>
          </div>
    </div>

    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
        <button type="button" class="btn btn-info" onclick="location.href='<?= $this->url('listaAvaliacoesDiariasAdm'); ?>'" style="float: right;margin-left: 10px;">
        <img src="<?php echo $this->basePath('img/diaria.png') ?>" alt="Novo">
        Diária</button>

        <button type="button" class="btn btn-success" onclick="location.href='<?= $this->url('listaAvaliacoesCallCenterAdm'); ?>'" style="float: right;margin-left: 10px;">
        <img src="<?php echo $this->basePath('img/telefone.png') ?>" alt="Novo">
        Call center</button>

        <button type="button" class="btn btn-warning" onclick="location.href='<?= $this->url('listaAvaliacaoAdm', array('tipo' => 'M')); ?>'" style="float: right;margin-left: 10px;">
        <img src="<?php echo $this->basePath('img/medico.png') ?>" alt="Novo">
        Médicos</button>

        <button type="button" class="btn btn-danger" onclick="location.href='<?= $this->url('listaAvaliacaoAdm', array('tipo' => 'C')); ?>'" style="float: right;">
        <img src="<?php echo $this->basePath('img/clinica.png') ?>" alt="Novo">
        Clínicas</button>
    </div>
    <!-- LISTAGEM DAS AVALIAÇÕES -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de avaliações</h3>
            </div>
            <div class="panel-body">
              <?php if($avaliacoes->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Empresa</th>
                    <?php if($tipoAvaliacao == 'M'): ?>
                    <th style="text-align: center">Médico</th>
                    <?php endif; ?>
                    <th style="text-align: center">Mês</th>
                    <th style="text-align: center">Ano</th>
                    <th style="text-align: center">Visualizar avaliaçãoes</th>
                </tr>
                <?php foreach($avaliacoes as $avaliacao): ?>
                <tr>
                  <td style="text-align: center"><?= $avaliacao['nome_empresa']; ?></td>
                  <?php if($tipoAvaliacao == 'M'): ?>
                    <td style="text-align: center"><?= $avaliacao['nome_medico']; ?></td>
                  <?php endif; ?>
                  <td style="text-align: center"><?= $this->numeroMes($avaliacao['mes']); ?></td>
                  <td style="text-align: center"><?= $avaliacao['ano']; ?></td>
                  <td style="text-align: center;">
                  <?php if($tipoAvaliacao == 'C'): ?>
                    <img src="<?= $this->basePath('img/visualizar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('avaliacaoAgendamentoAdm', array('mes' => $avaliacao['mes'], 'ano' => $avaliacao['ano'], 'empresa' => $avaliacao['empresa'])); ?>'" style="cursor: pointer;">
                    
                    <span style="margin-right:4px;"></span> 
                    
                    <img src="<?= $this->basePath('img/planilha.png'); ?>" title="Download planílha" 
                    onclick="location.href='<?= $this->url('planilhaCliente', array('mes' => $avaliacao['mes'], 'ano' => $avaliacao['ano'], 'empresa' => $avaliacao['empresa'])); ?>'" style="cursor: pointer;">

      

                  <?php else: ?>
                    <img src="<?= $this->basePath('img/visualizar.png'); ?>" title="Editar" 
                      onclick="location.href='<?= $this->url('avaliacaoQualitativaAdm', array('id' => $avaliacao['id'])); ?>'" style="cursor: pointer;">
                    
                    <span style="margin-right:4px;"></span> 
                    
                    <img src="<?= $this->basePath('img/planilha.png'); ?>" title="Download planílha" 
                    onclick="location.href='<?= $this->url('planilhaMedico', array('qualitativa' => $avaliacao['id'])); ?>'" style="cursor: pointer;">

                <?php endif; ?>
                    
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhuma avaliação encontrada!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($avaliacoes,
                                        'Sliding',
                                        'view/paginator', array('route' => 'listaAvaliacaoAdm', 'parametros' => array('tipo' => $tipoAvaliacao))); 
          ?>
        </div>
      </div>