    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Avaliação qualitativa do mês de <?= $this->numeroMes($periodo->mes_referencia); ?>/<?= $periodo->ano_referencia; ?> - <?= $medico->nome_medico; ?></h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/umacoluna', array('form'=> $formAvaliacao, 'route'=> '', 'botao' => '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>
    
    <style type="text/css">
      label{
        width: 100%;
      }
    </style>

    <script type="text/javascript">
      $(document).ready(function() {
        window.print();
        history.back(1);
      });
    </script>