 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('medicoIndex'); ?>">Avaliações</a></li>
      <li class="active">Avaliação qualitativa</li>
      <li>PID</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Avaliação qualitativa do mês de <?= $this->numeroMes($periodo->mes_referencia); ?>/<?= $periodo->ano_referencia; ?> - <?= $medico->nome_medico; ?></h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php 
                    $urlParams = array('medico' => $medico->id, 'periodo' => $periodo->id);
                    if($avaliacao){
                      $urlParams['idAvaliacao'] = $avaliacao->id;
                    }
                    $btnImprimir = '
                      <button type="button" onclick="location.href='."'".$this->url('imprimirAvaliacaoQualitativa', $urlParams)."'".'" class="btn btn-default" style="float: right;margin-right: 10px;">
                        <img src="'.$this->basePath('img/imprimir.png').'" alt="Imprimir" title="Imprimir">
                        Imprimir avaliação
                      </button>';
                  ?>
                  <?php echo $this->partial('form/umacoluna', array('form'=> $formAvaliacao, 'route'=> '', 'imprimir' => $btnImprimir)) ?>

            </div>
          </div>
      </div>
    </div>
    </div>