    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
       <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('inserirAvaliacoes'); ?>'" style="float: right;width:100px;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo</button>
    </div>
    <!-- LISTAGEM DOS CHAMADOS -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de liberações de avaliação</h3>
            </div>
            <div class="panel-body">
              <?php if($liberacoes->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Aba</th>
                    <th style="text-align: center">Mês referência</th>
                    <th style="text-align: center">Data de início</th>
                    <th style="text-align: center">Data de término</th>
                    <th style="text-align: center">Data da liberação</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($liberacoes as $liberacao): ?>
                <?php $aba = $liberacao['aba'] == 'C' ? 'Clínicas' : 'Médicos';  ?>
                <tr>
                  <td style="text-align: center"><?= $aba; ?></td>
                  <td style="text-align: center"><?= $this->numeroMes($liberacao['mes_referencia']); ?></td>
                  <td style="text-align: center"><?= $this->converterData($liberacao['inicio']); ?></td>
                  <td style="text-align: center"><?= $this->converterData($liberacao['termino']); ?></td>
                  <td style="text-align: center"><?= $this->converterData($liberacao['data_hora_liberacao']); ?></td>
                  <td style="text-align: center;">
                     <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('alterarLiberacao', array('id' => $liberacao['id'])); ?>'" style="cursor: pointer;">

                    <span style="margin-right:4px;"></span>

                    <img src="<?= $this->basePath('img/deletar.png'); ?>" title="Deletar" style="cursor: pointer;" onclick="alerta('<?= $this->url('liberacaoDeletar', array('id' => $liberacao['id'])) ?>', 'deletar');">
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhuma liberação de avaliação encontrada!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($liberacoes,
                                        'Sliding',
                                        'view/paginator', array('route' => 'listaLiberacoes')); 
          ?>
        </div>
      </div>